export const FETCH_SUCCESS_AUTH = 'FETCH_SUCCESS_AUTH';
export const LOGOUT = 'LOGOUT';
export const FETCH_ERROR_AUTH = 'FETCH_ERROR_AUTH';
export const FETCH_REQUEST_AUTH = 'FETCH_REQUEST_AUTH';
export const FETCH_SUCCESS_TOKEN = 'FETCH_SUCCESS_TOKEN';
