export const FETCH_REQUEST_ENTRIES = 'FETCH_REQUEST_ENTRIES';
export const FETCH_ERROR_ENTRIES = 'FETCH_ERROR_ENTRIES';
export const FETCH_SUCCESS_ENTRIES = 'FETCH_SUCCESS_ENTRIES';
export const DELETE_ENTRY = 'DELETE_ENTRY';
